export const ADD_USER = 'ADD_USER';
export const SET_CUSTOMER_DD = 'SET_CUSTOMER_DD';
export const SET_VEHICLE_DD = 'SET_VEHICLE_DD';
export const SET_VEHICLE_BY_USER_ID = 'SET_VEHICLE_BY_USER_ID';
export const REMOVE_USER = 'REMOVE_USER';
export const BOOKING_DETAILS = 'BOOKING_DETAILS';
export const RESET_BOOKING_DETAILS = 'RESET_BOOKING_DETAILS';
